name: vlpim
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # Python version
  - python=3.10

  # Core scientific computing
  - pandas>=1.5.0
  - numpy>=1.21.0
  - scipy>=1.9.0

  # HTTP requests
  - requests>=2.28.0
  - urllib3>=1.26.0

  # Configuration and data handling
  - pyyaml>=6.0
  - pathlib2

  # Visualization (optional)
  - matplotlib>=3.5.0
  - seaborn>=0.11.0

  # Progress bars
  - tqdm>=4.64.0

  # File handling
  - openpyxl>=3.0.0

  # Development tools (optional)
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  - black>=22.0.0
  - flake8>=5.0.0
  - mypy>=0.991

  # System tools
  - git
  - wget
  - curl

  # Note: External tools need to be installed separately:
  # - ProteinMPNN (from GitHub)
  # - NetMHCIIpan (from CBS)
  # - AlphaFold3 (from DeepMind)
  # - Rosetta (from University of Washington)

  # Pip dependencies (for packages not available in conda)
  - pip
  - pip:
    - typing-extensions>=4.0.0
